CREATE TABLE MT_OLO_XOG_TEMP AS /* FoldStart : */
SELECT XO.INDIVIDUAL_ID,
       MAX(CASE
               WHEN XO.DC_ONLINE_FIRST_DT IS NULL
                    AND XO.DC_LAST_APS_ORD_DT IS NULL
                    AND XO.DC_CDB_LAST_ORD_DT IS NULL THEN NULL
               WHEN NVL(TO_CHAR(TRUNC(XO.DC_CORP_FIRST_DT),'YYYYMMDD'),'00000000') = NVL(TO_CHAR(TRUNC(XO.DC_ONLINE_FIRST_DT),'YYYYMMDD'),'99999999')
                    OR NVL(TO_CHAR(TRUNC(XO.DC_CORP_FIRST_DT),'YYYYMMDD'),'00000000') = NVL(TO_CHAR(TRUNC(XO.DC_LAST_APS_ORD_DT),'YYYYMMDD'),'99999999')
                    OR NVL(TO_CHAR(TRUNC(XO.DC_CORP_FIRST_DT),'YYYYMMDD'),'00000000') = NVL(TO_CHAR(TRUNC(XO.DC_CDB_LAST_ORD_DT),'YYYYMMDD'),'99999999')THEN 1
               ELSE 0
           END) AS DC_CORP_FIRST_IND,
       MAX(CASE
               WHEN XO.DC_ONLINE_FIRST_DT IS NULL
                    AND XO.DC_OFFLINE_FIRST_DT IS NULL
                    AND XO.DC_LAST_APS_ORD_DT IS NULL
                    AND XO.DC_CDB_LAST_ORD_DT IS NULL THEN NULL
               WHEN NVL(TO_CHAR(TRUNC(XO.DC_CORP_FIRST_DT),'YYYYMMDD'),'00000000') = NVL(TO_CHAR(TRUNC(XO.DC_ONLINE_FIRST_DT),'YYYYMMDD'),'99999999')
                    OR NVL(TO_CHAR(TRUNC(XO.DC_CORP_FIRST_DT),'YYYYMMDD'),'00000000') = NVL(TO_CHAR(TRUNC(XO.DC_OFFLINE_FIRST_DT),'YYYYMMDD'),'99999999')
                    OR NVL(TO_CHAR(TRUNC(XO.DC_CORP_FIRST_DT),'YYYYMMDD'),'00000000') = NVL(TO_CHAR(TRUNC(XO.DC_LAST_APS_ORD_DT),'YYYYMMDD'),'99999999')
                    OR NVL(TO_CHAR(TRUNC(XO.DC_CORP_FIRST_DT),'YYYYMMDD'),'00000000') = NVL(TO_CHAR(TRUNC(XO.DC_CDB_LAST_ORD_DT),'YYYYMMDD'),'99999999')THEN 1
               ELSE 0
           END) AS DC_CORP_FIRST_IND2,
       MAX(CASE
               WHEN OLO.ORD_DT IS NULL THEN NULL
               WHEN NVL(TO_CHAR(TRUNC(XO.DC_OFFLINE_FIRST_DT),'YYYYMMDD'),'00000000') = NVL(TO_CHAR(TRUNC(OLO.ORD_DT),'YYYYMMDD'),'99999999') THEN 1
               ELSE 0
           END) AS DC_OFFLINE_FST_CRT_IND,
       MAX(CASE
               WHEN OLO.ORD_DT IS NULL THEN NULL
               WHEN NVL(TO_CHAR(TRUNC(XO.DC_CORP_FIRST_DT),'YYYYMMDD'),'00000000') = NVL(TO_CHAR(TRUNC(OLO.ORD_DT),'YYYYMMDD'),'99999999') THEN 1
               ELSE 0
           END) AS DC_CORP_FST_CRT_IND
FROM PROD.AGG_INDIVIDUAL_XOGRAPHIC XO
LEFT JOIN PROD.AGG_DIGITAL_ORDER OLO ON XO.INDIVIDUAL_ID = OLO.INDIVIDUAL_ID
GROUP BY XO.INDIVIDUAL_ID;
/* FoldEnd   : */

CREATE TABLE MT_OLI_APS_TEMP AS /* FoldStart : */
SELECT XO.INDIVIDUAL_ID,
       MAX(CASE
               WHEN OLI.CRT_DT IS NULL THEN NULL
               WHEN NVL(TO_CHAR(TRUNC(XO.DC_LAST_APS_ORD_DT),'YYYYMMDD'),'00000000') = NVL(TO_CHAR(TRUNC(OLI.CRT_DT),'YYYYMMDD'),'99999999') THEN 1
               ELSE 0
           END) AS DC_LAST_APS_CRT_IND
FROM PROD.AGG_INDIVIDUAL_XOGRAPHIC XO
LEFT JOIN PROD.AGG_DIGITAL_ITEM OLI ON XO.INDIVIDUAL_ID = OLI.INDIVIDUAL_ID
AND OLI.MAG_CD IN ('NCBK',
                   'UCBK',
                   'NCPR',
                   'UCPR')
GROUP BY XO.INDIVIDUAL_ID;
/* FoldEnd   : */

CREATE TABLE MT_OLI_XOG_TEMP AS /* FoldStart : */
SELECT XO.INDIVIDUAL_ID,
       MAX(CASE
               WHEN OLI.CRT_DT IS NULL THEN NULL
               WHEN NVL(TO_CHAR(TRUNC(XO.DC_ONLINE_FIRST_DT),'YYYYMMDD'),'00000000') = NVL(TO_CHAR(TRUNC(OLI.CRT_DT),'YYYYMMDD'),'99999999') THEN 1
               ELSE 0
           END) AS DC_ONLINE_FST_CRT_IND,
       MAX(CASE
               WHEN XO.DC_LAST_APS_ORD_DT IS NULL THEN NULL
               WHEN NVL(TO_CHAR(TRUNC(XO.DC_ONLINE_FIRST_DT),'YYYYMMDD'),'00000000') = NVL(TO_CHAR(TRUNC(XO.DC_LAST_APS_ORD_DT),'YYYYMMDD'),'99999999') THEN 1
               ELSE 0
           END) AS DC_ONLINE_FST_APS_IND
FROM PROD.AGG_INDIVIDUAL_XOGRAPHIC XO
LEFT JOIN PROD.AGG_DIGITAL_ITEM OLI ON XO.INDIVIDUAL_ID = OLI.INDIVIDUAL_ID
GROUP BY XO.INDIVIDUAL_ID;
/* FoldEnd   : */
